version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:3000"
      - "4443:443"
    volumes:
      - ./:/var/www/html
    environment:
      - ALLOW_OVERRIDE=true
    command: tail -f /dev/null
    container_name: hl_web
    links:
    - db
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rails_test
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=password
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "db-data:/var/lib/postgresql/data"
    container_name: hl_db

volumes:
  db-data:
