name: "My composite action deploy"
description: "Checks out the repository and does something"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - run: |
      echo "Executing action"
    shell: bash
