# Latest Ubuntu LTS
FROM i386/ruby:2.6.10

# RUN apt-get -y update && apt-get -y upgrade

# RUN gem install bundler

# RUN gem update --system 3.2.3

# WORKDIR /var/www/html

# RUN /bin/bash -l -c "bundle install"

CMD ["bundle", "exec", "rails", "server"]
