default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: password
  host: rails_test
  timeout: 5000

development:
  <<: *defaults
  database: realty_development

test:
  <<: *defaults
  database: realty_test

staging:
  <<: *defaults
  database: realty_development

production:
  <<: *defaults
  database: realty_production
