default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] { rails } %>
  password: <%= ENV['POSTGRES_PASSWORD'] { password } %>
  host: <%= ENV['POSTGRES_HOST'] { localhost } %>
  timeout: <%= ENV['POSTGRES_TIMEOUT'] { 5000 } %>

development:
  <<: *default
  database: realty_development

test:
  <<: *default
  database: realty_test

staging:
  <<: *default
  database: realty_development

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] { realty_production } %>
