name: "CI"
on:
  push:
    branches: [ "*" ]
jobs:
  build:
    name: "Build - ${{ github.event_name }}"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432
          POSTGRES_DB: rails_test
          POSTGRES_TIMEOUT: 5000
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
      - name: Setup database
        run: bin/rails db:structure:load
      - name: Run tests
        run: bin/bundle exec rspec
      - name: Qa
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/heads/qa_/ ]]; then
            echo "Faça deploy para QA"
          fi
  deploy:
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/qa_*' || github.ref == 'refs/heads/qa' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: actions/checkout@v3

      - name: Deploy Qa
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/heads/qa_/ || "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "Faça deploy para QA"
          fi

      - name: Deploy Production
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Faça deploy para produção"
          fi
