name: "CI/CD with Development"

on:
  workflow_dispatch:
    if: github.event.pull_request.head.ref == '^lead-'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development
        run: echo "Deploy to Development"
