name: "CI/CD with GitHub Actions"

on: [push]

jobs:
  check_environment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Imprimir o ambiente
        run: |
          if [ ${{ vars.CURRENT_ENV }} == "development" ]; then
            echo "Ambiente de desenvolvimento"
          elif [ ${{ vars.CURRENT_ENV }} == "qa" ]; then
            echo "Ambiente de QA"
          elif [ ${{ vars.CURRENT_ENV }} == "production" ]; then
            echo "Ambiente de produção"
          else
            echo "Ambiente não encontrado"
          fi
