name: "CI/CD with Development"

on:
  pull_request:
    branches: [ '^lead-*' ]
    types:
      - opened
      - synchronize

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development
        run: echo "Deploy to Development"
