name: "CI/CD with Development"

on:
  repository_dispatch:
    types: [deploy-event]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development
        run: echo "Deploy to Development"
