# TODO: Apenas um exemplo, vai precisar de ajustes
name: "CI/CD with Main"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Verify Environment
        uses: actions/checkout@v3
      - name: Migrate Main
        run: echo "Rode as migrations"
      - name: Data Migrate Main
        run: echo "Rode as data migrations"
      - name: Deploy Main
        run: |
          echo "Faça deploy para Main"
          # gcloud beta run jobs create neurolead-migration-job \
          # --image ${{ vars.IMAGE_DOCKFILE_APPLICATION }} \
          # --command "bundle exec rake db:migrate" \
          # --execute-now --wait
