name: "CI/CD with Qa"

on:
  repository_dispatch:
    types: [deploy-event]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Qa
        run: echo "Deploy to Qa"
