name: "CI/CD with Qa"
on:
  push:
    branches: [ qa ]
jobs:
  deploy:
    needs: [testing]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Qa
        run: echo "Deploy to Qa"
