# TODO: Apenas um exemplo, vai precisar de ajustes
name: "CI/CD with Qa"

on:
  push:
    branches: [ qa ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && (github.ref == 'refs/heads/qa' || github.ref == '^refs/heads/qa_')) }}
    steps:
      - name: Verify Environment
        uses: actions/checkout@v3
      - name: Migrate QA
        run: echo "Rode as migrations"
      - name: Data Migrate QA
        run: echo "Rode as data migrations"
      - name: Deploy Qa
        run: |
          echo "Faça deploy para QA"
          # gcloud beta run jobs create neurolead-migration-job \
          # --image ${{ vars.IMAGE_DOCKFILE_APPLICATION }} \
          # --command "bundle exec rake db:migrate" \
          # --execute-now --wait
      - name: Ta
        run: echo "${{needs.test.outputs.test-passed}}"
